# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91b84bdd2c15330e1428268d09fb5393dbc263ab4b85764ff278a53fa1d9fdd6a2a8ec1b76dd5d579b647d66c9deab5be81d1f662d52805badab9336479ff140

test:
  secret_key_base: b4bd207d5fdf99d1e4e08a4df35d33c91bc644622b52ad42171f8e5e6200bc8471996caa823a52916121dbc64c0ab6e001af159873c8a04959f710a47fc361d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
